//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public int PlaneId { get; set; }
        public string PlaneModel { get; set; }
        public Nullable<int> RouteId { get; set; }
    
        public virtual PlaneRoute PlaneRoute { get; set; }
    }
}
